import { ItemProps } from './../../models/common.d';
import { DataColumnInvestType, PackageInvest } from "models/invest";

export const investListData =
    [
        {
            id: 1,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '50000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 2,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '30000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '20/1/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 3,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '10000000',
            lai_hang_thang: '19000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '12 tháng',
            tong_lai_du_kien: '1100000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '12 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 4,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '80000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 5,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '1000000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '11/6/2022',
            ki_han_dau_tu: '8 tháng',
            tong_lai_du_kien: '1289000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '2%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '8 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 6,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '80000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 7,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '100000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '24 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '24 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        }
    ] as PackageInvest[];

export const investListMoreData =
    [
        {
            id: 8,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '50000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 9,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '30000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '20/1/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 10,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '10000000',
            lai_hang_thang: '19000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '12 tháng',
            tong_lai_du_kien: '1100000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '12 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 11,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '80000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 12,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '1000000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '11/6/2022',
            ki_han_dau_tu: '8 tháng',
            tong_lai_du_kien: '1289000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '2%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '8 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 13,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '80000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '6 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '6 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        },
        {
            id: 14,
            ma_hop_dong: 'HĐCC/ĐKOTO/TPHN79HĐ/2212/04',
            so_tien_dau_tu: '100000000',
            lai_hang_thang: '12000',
            ngay_dau_tu: '12/12/2022',
            ki_han_dau_tu: '24 tháng',
            tong_lai_du_kien: '3984000',
            tong_lai_da_nhan: '',
            tong_lai_da_tra: '',
            ngay_dao_han: '',
            hinh_thuc_tra_lai: 'Lãi hàng tháng, gốc cuối kỳ',
            ti_le_lai_suat_hang_thang: '1%',
            ti_le_lai_suat_hang_nam: '12%',
            trang_thai_hop_dong: '',
            ngay_dao_han_du_kien: '01/01/2023',
            tong_lai_nhan_duoc: '1000000',
            thoi_gian_dau_tu: '24 tháng',
            tong_goc_con_lai: '',
            tong_goc_da_tra: '',
        }
    ] as PackageInvest[];

export const amountListData = [
    {
        id: '1',
        text: 'Dưới 10,000,000 VNĐ',
        value: 'Dưới 10,000,000 VNĐ',
    },
    {
        id: '2',
        text: '10,000,000 VNĐ - dưới 50,000,000 VNĐ',
        value: '10,000,000 VNĐ - dưới 50,000,000 VNĐ',
    },
    {
        id: '3',
        text: '50,000,000 VNĐ - dưới 100,000,000 VNĐ',
        value: '50,000,000 VNĐ - dưới 100,000,000 VNĐ',
    },
    {
        id: '4',
        text: 'Trên 100,000,000 VNĐ',
        value: 'Trên 100,000,000 VNĐ',
    }
]
export const dateListData = [
    {
        id: '1',
        text: '1 tháng',
        value: '1 tháng',
    },
    {
        id: '2',
        text: '3 tháng',
        value: '3 tháng',
    },
    {
        id: '3',
        text: '6 tháng',
        value: '6 tháng',
    },
    {
        id: '4',
        text: '12 tháng',
        value: '12 tháng',
    },
    {
        id: '5',
        text: '18 tháng',
        value: '18 tháng',
    },
    {
        id: '6',
        text: '24 tháng',
        value: '24 tháng',
    }
]

export const dataColumnInvest: DataColumnInvestType[] = [
    {
        id: '1',
        receivingPeriod: 'Kỳ 1',
        principalAmount: '1,000,000,000',
        profitAmount: '1,000,000,000',
        total: '1,000,000',
        receivedDate: '12/05/2023'
    },
    {
        id: '2',
        receivingPeriod: 'Kỳ 2',
        principalAmount: '1,000,000,000',
        profitAmount: '1,000,000',
        total: '1,000,000',
        receivedDate: '12/06/2023'
    },
    {
        id: '3',
        receivingPeriod: 'Kỳ 3',
        principalAmount: '1,000,000,000',
        profitAmount: '1,000,000',
        total: '1,000,000',
        receivedDate: '12/07/2023'
    },
    {
        id: '4',
        receivingPeriod: 'Kỳ 4',
        principalAmount: '1,000,000,000',
        profitAmount: '1,000,000',
        total: '1,000,000',
        receivedDate: '12/08/2023'
    }
];

export const columnName = ['STT', 'Kỳ nhận', 'Số tiền gốc', 'Số tiền lãi', 'Tổng tiền', 'Ngày nhận'];

